CPP=g++
CPP_FLAGS=-std=c++11 -O3
INCLUDE_PATH=-I. -I./include
LIBRARY_PATH=-L. -L./lib
LIB=-lAlgorithm

editDistance: main.cpp
	${CPP} ${CPP_FLAGS} -o editDistance main.cpp ${INCLUDE_PATH} ${LIBRARY_PATH} ${LIB}
